server:
  servlet:
    session:
      cookie:
        name: cloudhub_session
  tomcat:
    connection-timeout: -1

logging:
  charset:
    console: UTF-8
  level:
    org.huel.cloudhub: debug

spring:
  application:
    name: Cloudhub Disk Client
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 5000MB
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  cache:
    type: caffeine
  web:
    resources:
      add-mappings: false
